import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import cron from 'node-cron';
import pg from 'pg';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import dns from 'node:dns/promises';
import net from 'node:net';
import crypto from 'node:crypto';

const { Pool } = pg;
const app = express();
const port = Number(process.env.PORT || 10000);
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : undefined });
const activeTasks = new Map();
const JWT_SECRET = process.env.JWT_SECRET || 'change-this-secret-in-production';
const allowedOrigins = (process.env.FRONTEND_URL || 'https://cronflow.onrender.com').split(',').map(x => x.trim().replace(/\/$/, '')).filter(Boolean);
app.use(cors({ origin(origin, cb) { if (!origin || allowedOrigins.includes(origin.replace(/\/$/, ''))) return cb(null, true); cb(new Error('CORS origin not allowed')); }, methods:['GET','POST','PATCH','DELETE','OPTIONS'], allowedHeaders:['Content-Type','Authorization'] }));
app.use(express.json({ limit:'512kb' }));

const schema = `
create extension if not exists pgcrypto;
create table if not exists users(id uuid primary key default gen_random_uuid(),email text unique not null,password_hash text not null,created_at timestamptz not null default now());
create table if not exists cron_jobs(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,name text not null,url text not null,method text not null default 'GET',headers jsonb not null default '{}'::jsonb,body text,schedule text not null,timezone text not null default 'UTC',enabled boolean not null default true,last_run_at timestamptz,last_status text,created_at timestamptz not null default now(),retry_count integer not null default 0,retry_delay integer not null default 30,tags jsonb not null default '[]'::jsonb,secrets_enc text);
create table if not exists job_executions(id uuid primary key default gen_random_uuid(),job_id uuid not null references cron_jobs(id) on delete cascade,user_id uuid not null references users(id) on delete cascade,started_at timestamptz not null default now(),finished_at timestamptz,status text not null,status_code integer,response_time_ms integer,error_message text,response_headers jsonb,response_body text,attempt integer not null default 1);
create table if not exists status_pages(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,slug text unique not null,name text not null,public boolean not null default true,created_at timestamptz not null default now());
create table if not exists status_page_jobs(page_id uuid not null references status_pages(id) on delete cascade,job_id uuid not null references cron_jobs(id) on delete cascade,position integer not null default 0,primary key(page_id,job_id));
create index if not exists cron_jobs_user_id_idx on cron_jobs(user_id); create index if not exists job_executions_user_id_idx on job_executions(user_id); create index if not exists job_executions_job_id_idx on job_executions(job_id); create index if not exists job_executions_user_started_idx on job_executions(user_id,started_at desc);
`;
async function initDb(){await pool.query(schema);for(const q of [`alter table cron_jobs add column if not exists retry_count integer not null default 0`,`alter table cron_jobs add column if not exists retry_delay integer not null default 30`,`alter table cron_jobs add column if not exists tags jsonb not null default '[]'::jsonb`,`alter table cron_jobs add column if not exists secrets_enc text`,`alter table job_executions add column if not exists response_headers jsonb`,`alter table job_executions add column if not exists response_body text`,`alter table job_executions add column if not exists attempt integer not null default 1`])await pool.query(q);}
function signUser(u){return jwt.sign({id:u.id,email:u.email},JWT_SECRET,{expiresIn:'30d'});}function auth(req,res,next){const t=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!t)return res.status(401).json({error:'Missing access token'});try{req.user=jwt.verify(t,JWT_SECRET);next();}catch{return res.status(401).json({error:'Invalid or expired access token'});}}
function validUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password;}catch{return false;}}
function privateIp(ip){if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||p[0]===0;}if(net.isIPv6(ip)){const x=ip.toLowerCase();return x==='::1'||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe80:');}return true;}
async function assertSafeUrl(raw){if(!validUrl(raw))throw new Error('Only public HTTP and HTTPS URLs are allowed');const u=new URL(raw);if(['localhost','localhost.localdomain'].includes(u.hostname.toLowerCase()))throw new Error('Local addresses are blocked');const records=await dns.lookup(u.hostname,{all:true,verbatim:true});if(!records.length||records.some(r=>privateIp(r.address)))throw new Error('Private or internal network addresses are blocked');return u;}
function key(){return crypto.createHash('sha256').update(JWT_SECRET).digest();}function enc(obj){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv);const data=Buffer.concat([c.update(JSON.stringify(obj),'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),data]).toString('base64');}function dec(v){if(!v)return{};const b=Buffer.from(v,'base64'),d=crypto.createDecipheriv('aes-256-gcm',key(),b.subarray(0,12));d.setAuthTag(b.subarray(12,28));return JSON.parse(Buffer.concat([d.update(b.subarray(28)),d.final()]).toString());}
function substitute(value,secrets){return String(value??'').replace(/\{\{\s*([A-Za-z0-9_]+)\s*\}\}/g,(_,k)=>secrets[k]??`{{${k}}}`);}
async function executeJob(job){let secrets={};try{secrets=dec(job.secrets_enc);}catch{}let attempt=0,last={status:'failed',statusCode:null,errorMessage:null,responseTime:0,headers:{},body:''};const max=Math.max(0,Math.min(5,Number(job.retry_count||0)));while(attempt<=max){attempt++;const started=Date.now();let status='failed',statusCode=null,errorMessage=null,responseHeaders={},responseBody='';try{const raw=substitute(job.url,secrets);const u=await assertSafeUrl(raw);const headers=Object.fromEntries(Object.entries(job.headers||{}).map(([k,v])=>[k,substitute(v,secrets)]));const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),Number(process.env.REQUEST_TIMEOUT_MS||30000));const response=await fetch(u,{method:job.method||'GET',headers,body:['GET','HEAD'].includes(job.method||'GET')?undefined:substitute(job.body||'',secrets),signal:controller.signal,redirect:'manual'});clearTimeout(timer);statusCode=response.status;responseHeaders=Object.fromEntries(response.headers.entries());responseBody=(await response.text()).slice(0,100000);status=response.ok?'success':'failed';if(response.status>=300&&response.status<400){const loc=response.headers.get('location');if(loc){const next=new URL(loc,u).toString();await assertSafeUrl(next);errorMessage=`Redirect blocked for security. Target: ${next}`;}}}catch(e){errorMessage=e.name==='AbortError'?'Request timed out':e.message;}const responseTime=Date.now()-started;last={status,statusCode,errorMessage,responseTime,headers:responseHeaders,body:responseBody};if(status==='success'||attempt>max)break;if(job.retry_delay)await new Promise(r=>setTimeout(r,Math.min(300000,Number(job.retry_delay)*1000)));}
await pool.query(`insert into job_executions(job_id,user_id,started_at,finished_at,status,status_code,response_time_ms,error_message,response_headers,response_body,attempt) values($1,$2,$3,now(),$4,$5,$6,$7,$8,$9,$10)`,[job.id,job.user_id,new Date(Date.now()-last.responseTime),last.status,last.statusCode,last.responseTime,last.errorMessage,last.headers,last.body,attempt]);await pool.query(`update cron_jobs set last_run_at=now(),last_status=$1 where id=$2`,[last.status,job.id]);return last;}
function scheduleJob(job){if(activeTasks.has(job.id)){activeTasks.get(job.id).stop();activeTasks.delete(job.id);}if(!job.enabled||!cron.validate(job.schedule))return;const task=cron.schedule(job.schedule,()=>executeJob(job).catch(console.error),{timezone:job.timezone||'UTC'});activeTasks.set(job.id,task);}
async function loadSchedules(){const{rows}=await pool.query(`select * from cron_jobs where enabled=true`);rows.forEach(scheduleJob);console.log(`Loaded ${rows.length} active cron jobs`);}
app.get('/health',(_q,r)=>r.json({ok:true,service:'cronflow-api',database:'neon',time:new Date().toISOString()}));
app.post('/api/auth/register',async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Enter a valid email address'});if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});try{const h=await bcrypt.hash(password,12),{rows}=await pool.query(`insert into users(email,password_hash) values($1,$2) returning id,email,created_at`,[email,h]);res.status(201).json({token:signUser(rows[0]),user:rows[0]});}catch(e){res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'An account with this email already exists':'Could not create account'});}});
app.post('/api/auth/login',async(req,res)=>{const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||''),{rows}=await pool.query(`select * from users where email=$1`,[email]);if(!rows[0]||!(await bcrypt.compare(password,rows[0].password_hash)))return res.status(401).json({error:'Invalid email or password'});res.json({token:signUser(rows[0]),user:{id:rows[0].id,email:rows[0].email,created_at:rows[0].created_at}});});
app.get('/api/auth/me',auth,async(req,res)=>{const{rows}=await pool.query(`select id,email,created_at from users where id=$1`,[req.user.id]);if(!rows[0])return res.status(401).json({error:'Account not found'});res.json({user:rows[0]});});
app.get('/api/jobs',auth,async(req,res)=>{const{rows}=await pool.query(`select * from cron_jobs where user_id=$1 order by created_at desc`,[req.user.id]);res.json(rows.map(j=>({...j,secrets_enc:undefined})));});
app.post('/api/jobs',auth,async(req,res)=>{const{name,url,method='GET',schedule,timezone='UTC',headers={},body=null,retry_count=0,retry_delay=30,tags=[],secrets={}}=req.body||{};if(!name||!url||!schedule)return res.status(400).json({error:'name, url and schedule are required'});try{await assertSafeUrl(url);}catch(e){return res.status(400).json({error:e.message});}if(!cron.validate(schedule))return res.status(400).json({error:'Invalid cron expression'});if(!['GET','POST','PUT','PATCH','DELETE','HEAD'].includes(method))return res.status(400).json({error:'Unsupported HTTP method'});const{rows}=await pool.query(`insert into cron_jobs(user_id,name,url,method,schedule,timezone,headers,body,retry_count,retry_delay,tags,secrets_enc) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning *`,[req.user.id,name,url,method,schedule,timezone,headers,body,Math.min(5,Math.max(0,Number(retry_count))),Math.min(300,Math.max(0,Number(retry_delay))),tags,enc(secrets)]);scheduleJob(rows[0]);res.status(201).json({...rows[0],secrets_enc:undefined});});
app.patch('/api/jobs/:id',auth,async(req,res)=>{const allowed=['name','url','method','schedule','timezone','headers','body','enabled','retry_count','retry_delay','tags'];const u=Object.fromEntries(Object.entries(req.body||{}).filter(([k])=>allowed.includes(k)));if(u.url)try{await assertSafeUrl(u.url);}catch(e){return res.status(400).json({error:e.message});}if(u.schedule&&!cron.validate(u.schedule))return res.status(400).json({error:'Invalid cron expression'});if(req.body?.secrets!==undefined)u.secrets_enc=enc(req.body.secrets||{});const keys=Object.keys(u);if(!keys.length)return res.status(400).json({error:'No valid fields supplied'});const vals=[req.params.id,req.user.id],sets=keys.map((k,i)=>{vals.push(k==='retry_count'?Math.min(5,Math.max(0,Number(u[k]))):k==='retry_delay'?Math.min(300,Math.max(0,Number(u[k]))):u[k]);return `${k}=$${i+3}`;});const{rows}=await pool.query(`update cron_jobs set ${sets.join(',')} where id=$1 and user_id=$2 returning *`,vals);if(!rows[0])return res.status(404).json({error:'Job not found'});scheduleJob(rows[0]);res.json({...rows[0],secrets_enc:undefined});});
app.delete('/api/jobs/:id',auth,async(req,res)=>{if(activeTasks.has(req.params.id)){activeTasks.get(req.params.id).stop();activeTasks.delete(req.params.id);}const r=await pool.query(`delete from cron_jobs where id=$1 and user_id=$2`,[req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({error:'Job not found'});res.status(204).end();});
app.post('/api/jobs/:id/run',auth,async(req,res)=>{const{rows}=await pool.query(`select * from cron_jobs where id=$1 and user_id=$2`,[req.params.id,req.user.id]);if(!rows[0])return res.status(404).json({error:'Job not found'});executeJob(rows[0]).then(result=>console.log('Manual run',result)).catch(console.error);res.status(202).json({queued:true});});
app.get('/api/executions',auth,async(req,res)=>{const limit=Math.min(30,Math.max(1,Number(req.query.limit||30)));const{rows}=await pool.query(`select e.*,j.name as job_name from job_executions e left join cron_jobs j on j.id=e.job_id where e.user_id=$1 order by e.started_at desc limit $2`,[req.user.id,limit]);res.json(rows);});
app.get('/api/executions/:id',auth,async(req,res)=>{const{rows}=await pool.query(`select e.*,j.name as job_name,j.url,j.method,j.headers,j.body,j.schedule,j.timezone from job_executions e join cron_jobs j on j.id=e.job_id where e.id=$1 and e.user_id=$2`,[req.params.id,req.user.id]);if(!rows[0])return res.status(404).json({error:'Execution not found'});res.json(rows[0]);});
app.get('/api/jobs/:id/analytics',auth,async(req,res)=>{const{rows}=await pool.query(`select count(*)::int total,count(*) filter(where status='success')::int success,count(*) filter(where status='failed')::int failed,coalesce(round(avg(response_time_ms)),0)::int avg_ms,max(started_at) last_run from job_executions where job_id=$1 and user_id=$2`,[req.params.id,req.user.id]);res.json(rows[0]);});
app.post('/api/status-pages',auth,async(req,res)=>{const name=String(req.body?.name||'My Status');let slug=(String(req.body?.slug||name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')).slice(0,60)||crypto.randomUUID().slice(0,8);const{rows}=await pool.query(`insert into status_pages(user_id,name,slug) values($1,$2,$3) returning *`,[req.user.id,name,slug]);res.status(201).json(rows[0]);});
app.get('/api/status-pages',auth,async(req,res)=>{const{rows}=await pool.query(`select p.*,coalesce(json_agg(json_build_object('id',j.id,'name',j.name,'enabled',j.enabled,'last_status',j.last_status)) filter(where j.id is not null),'[]') jobs from status_pages p left join status_page_jobs pj on pj.page_id=p.id left join cron_jobs j on j.id=pj.job_id where p.user_id=$1 group by p.id order by p.created_at desc`,[req.user.id]);res.json(rows);});
app.patch('/api/status-pages/:id',auth,async(req,res)=>{const{rows}=await pool.query(`update status_pages set name=coalesce($3,name),public=coalesce($4,public) where id=$1 and user_id=$2 returning *`,[req.params.id,req.user.id,req.body?.name,req.body?.public]);if(!rows[0])return res.status(404).json({error:'Status page not found'});res.json(rows[0]);});
app.post('/api/status-pages/:id/jobs',auth,async(req,res)=>{const{rows}=await pool.query(`select id from status_pages where id=$1 and user_id=$2`,[req.params.id,req.user.id]);if(!rows[0])return res.status(404).json({error:'Status page not found'});await pool.query(`insert into status_page_jobs(page_id,job_id) select $1,id from cron_jobs where id=$2 and user_id=$3 on conflict do nothing`,[req.params.id,req.body?.job_id,req.user.id]);res.json({ok:true});});
app.get('/api/public/status/:slug',async(req,res)=>{const{rows}=await pool.query(`select p.name,p.slug,p.public,j.name as job_name,j.last_status,j.last_run_at from status_pages p left join status_page_jobs pj on pj.page_id=p.id left join cron_jobs j on j.id=pj.job_id where p.slug=$1 and p.public=true`,[req.params.slug]);if(!rows.length)return res.status(404).json({error:'Status page not found'});res.json({name:rows[0].name,slug:rows[0].slug,jobs:rows.filter(x=>x.job_name).map(x=>({name:x.job_name,status:x.last_status==='success'?'operational':'degraded',last_run_at:x.last_run_at}))});});
app.get('/api/public/badge/:slug.svg',async(req,res)=>{const{rows}=await pool.query(`select p.name,coalesce(bool_and(j.last_status='success'),true) ok from status_pages p left join status_page_jobs pj on pj.page_id=p.id left join cron_jobs j on j.id=pj.job_id where p.slug=$1 and p.public=true group by p.id`,[req.params.slug]);if(!rows[0])return res.status(404).type('svg').send('<svg xmlns="http://www.w3.org/2000/svg" width="140" height="28"><text x="8" y="18">CronFlow: not found</text></svg>');const text=rows[0].ok?'operational':'degraded';res.type('svg').send(`<svg xmlns="http://www.w3.org/2000/svg" width="170" height="28" role="img"><rect width="170" height="28" rx="5" fill="#171c26"/><text x="10" y="18" fill="#fff" font-family="Arial" font-size="12">CronFlow: ${text}</text></svg>`);});
async function start(){if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is required');await initDb();app.listen(port,'0.0.0.0',async()=>{console.log(`CronFlow API running on port ${port}`);await loadSchedules();});}start().catch(e=>{console.error('Startup failed:',e);process.exit(1);});
