import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:10000',KEY='cronflow_token',TZ=Intl.DateTimeFormat().resolvedOptions().timeZone;
const schedules={'* * * * *':'Every minute','*/5 * * * *':'Every 5 minutes','*/15 * * * *':'Every 15 minutes','*/30 * * * *':'Every 30 minutes','0 * * * *':'Every hour','0 */6 * * *':'Every 6 hours','0 0 * * *':'Every day','0 0 * * 0':'Every week','0 0 1 * *':'Every month'};
const formDefaults=()=>({name:'',url:'',method:'GET',schedule:'*/5 * * * *',timezone:TZ,headers:'{}',body:''});
async function api(path,opt={},token=localStorage.getItem(KEY)){return fetch(API+path,{...opt,headers:{...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{}),...(token?{Authorization:`Bearer ${token}`}:{})}})}
function ago(v){if(!v)return'Never';let s=Math.max(0,(Date.now()-new Date(v))/1000);return s<60?`${Math.floor(s)}s ago`:s<3600?`${Math.floor(s/60)}m ago`:s<86400?`${Math.floor(s/3600)}h ago`:`${Math.floor(s/86400)}d ago`}
function App(){const[user,setUser]=useState(null),[jobs,setJobs]=useState([]),[history,setHistory]=useState([]),[view,setView]=useState('dashboard'),[modal,setModal]=useState(null),[drawer,setDrawer]=useState(null),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[toast,setToast]=useState(null),[auth,setAuth]=useState('login');
 const note=(m,bad=false)=>{setToast({m,bad});setTimeout(()=>setToast(null),2600)};
 useEffect(()=>{let t=localStorage.getItem(KEY);if(t)api('/api/auth/me',{},t).then(async r=>r.ok&&setUser((await r.json()).user))},[]);useEffect(()=>{if(user){load();loadHistory()}},[user]);
 async function load(){let r=await api('/api/jobs');if(r.ok)setJobs(await r.json())}async function loadHistory(){let r=await api('/api/executions');if(r.ok)setHistory(await r.json())}
 async function save(e){e.preventDefault();let f=new FormData(e.currentTarget),headers={};try{headers=JSON.parse(f.get('headers')||'{}')}catch{return note('Headers must be valid JSON',true)}let p={name:f.get('name'),url:f.get('url'),method:f.get('method'),schedule:f.get('schedule'),timezone:f.get('timezone'),headers,body:f.get('body')||null},edit=modal?.job;let r=await api(edit?`/api/jobs/${edit.id}`:'/api/jobs',{method:edit?'PATCH':'POST',body:JSON.stringify(p)}),d=await r.json().catch(()=>({}));if(!r.ok)return note(d.error||'Could not save job',true);setModal(null);load();note(edit?'Job updated':'Cron job created')}
 async function patch(j,p){let r=await api(`/api/jobs/${j.id}`,{method:'PATCH',body:JSON.stringify(p)});if(r.ok){load();note(p.enabled===false?'Job paused':p.enabled===true?'Job resumed':'Job updated')}else note('Could not update job',true)}
 async function run(j){let r=await api(`/api/jobs/${j.id}/run`,{method:'POST'});if(r.ok){note('Job queued');setTimeout(loadHistory,1200)}else note('Could not run job',true)}
 async function del(j){if(!confirm(`Delete “${j.name}”?`))return;let r=await api(`/api/jobs/${j.id}`,{method:'DELETE'});if(r.ok){load();setDrawer(null);note('Job deleted')}else note('Could not delete job',true)}
 async function duplicate(j){let p={name:j.name+' copy',url:j.url,method:j.method,schedule:j.schedule,timezone:j.timezone,headers:j.headers||{},body:j.body||null};let r=await api('/api/jobs',{method:'POST',body:JSON.stringify(p)});if(r.ok){load();note('Job duplicated')}else note('Could not duplicate job',true)}
 function logout(){localStorage.removeItem(KEY);setUser(null);setJobs([]);setHistory([])}
 const filtered=useMemo(()=>jobs.filter(j=>(filter==='all'||filter==='active'&&j.enabled||filter==='paused'&&!j.enabled||filter==='failed'&&j.last_status==='failed')&&(`${j.name} ${j.url}`.toLowerCase().includes(search.toLowerCase()))),[jobs,search,filter]);
 if(!user)return <Landing mode={auth}setMode={setAuth}onAuth={setUser}/>;let active=jobs.filter(j=>j.enabled).length,failed=jobs.filter(j=>j.last_status==='failed').length,success=history.filter(x=>x.status==='success').length;
 return <div className="shell"><aside><div className="brand"><i>C</i>CronFlow <b>2.0</b></div><nav>{[['dashboard','⌂','Dashboard'],['jobs','◷','Cron Jobs'],['history','↻','History'],['settings','⚙','Settings']].map(x=><button className={view===x[0]?'active':''}onClick={()=>setView(x[0])}key={x[0]}><em>{x[1]}</em>{x[2]}</button>)}</nav><div className="sidebottom"><div className="plan"><small>FREE PLAN</small><strong>{jobs.length} jobs</strong><span>{active} active · {failed} failed</span></div><button onClick={logout}>↪ Sign out</button></div></aside><main><header><div><small>AUTOMATION</small><h1>{view==='dashboard'?'Dashboard':view==='jobs'?'Cron Jobs':view==='history'?'Execution History':'Settings'}</h1></div><div className="system"><span/>All systems operational <b>{user.email?.[0]?.toUpperCase()}</b></div></header>{view==='dashboard'?<Dashboard jobs={jobs}history={history}active={active}failed={failed}success={success}create={()=>setModal({})}go={setView}run={run}toggle={patch}open={setDrawer}/>:view==='jobs'?<Jobs jobs={filtered}search={search}setSearch={setSearch}filter={filter}setFilter={setFilter}create={()=>setModal({})}edit={j=>setModal({job:j})}run={run}toggle={patch}del={del}dup={duplicate}open={setDrawer}/>:view==='history'?<History data={history}refresh={loadHistory}/>:<Settings user={user}/>}</main>{drawer&&<Drawer job={drawer}history={history.filter(x=>x.job_id===drawer.id)}close={()=>setDrawer(null)}edit={()=>{setModal({job:drawer});setDrawer(null)}}run={()=>run(drawer)}del={()=>del(drawer)}dup={()=>duplicate(drawer)}/>} {modal&&<Modal job={modal.job}close={()=>setModal(null)}save={save}/>} {toast&&<div className={'toast '+(toast.bad?'bad':'')}>{toast.bad?'!':'✓'} {toast.m}</div>}</div>}
function Dashboard({jobs,history,active,failed,success,create,go,run,toggle,open}){return <><section className="welcome"><div><small>WELCOME BACK</small><h2>Your automations at a glance.</h2><p>Schedule, monitor, and control your HTTP jobs.</p></div><button className="primary"onClick={create}>＋ Create Cron Job</button></section><div className="stats"><Stat t="Total Jobs"v={jobs.length}i="◫"/><Stat t="Active Jobs"v={active}i="✓"/><Stat t="Failed Jobs"v={failed}i="!"bad={failed>0}/><Stat t="Successful Runs"v={success}i="↗"/></div><div className="twocol"><section className="panel"><Head title="Active jobs"sub="Your scheduled automations."action="View all →"onClick={()=>go('jobs')}/>{jobs.filter(j=>j.enabled).slice(0,6).map(j=><JobRow key={j.id}j={j}run={run}toggle={toggle}open={open}/>)}{!active&&<Empty create={create}/>}</section><section className="panel"><Head title="Recent executions"sub="Latest scheduler activity."action="History →"onClick={()=>go('history')}/>{history.slice(0,7).map(x=><div className="exec"key={x.id}><span className={'dot '+x.status}/><div><strong>{x.job_name||'Job'}</strong><small>{ago(x.started_at)} · {x.status_code||'Error'}</small></div><b>{x.response_time_ms?x.response_time_ms+'ms':'—'}</b></div>)}{!history.length&&<EmptyText/>}</section></div></>}
function Jobs({jobs,search,setSearch,filter,setFilter,create,edit,run,toggle,del,dup,open}){return <section className="panel full"><Head title="All Cron Jobs"sub="Manage every scheduled HTTP request."action="＋ Create Cron Job"onClick={create}primary/><div className="toolbar"><div className="search">⌕<input value={search}onChange={e=>setSearch(e.target.value)}placeholder="Search jobs or URLs..."/></div><div className="filters">{[['all','All'],['active','Active'],['paused','Paused'],['failed','Failed']].map(x=><button className={filter===x[0]?'sel':''}onClick={()=>setFilter(x[0])}key={x[0]}>{x[1]}</button>)}</div></div>{jobs.length?<div className="table"><table><thead><tr><th>Job</th><th>Schedule</th><th>Method</th><th>Status</th><th>Last run</th><th/></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><button className="jobcell"onClick={()=>open(j)}><i>◉</i><span><strong>{j.name}</strong><small>{j.url}</small></span></button></td><td><strong>{schedules[j.schedule]||'Custom'}</strong><code>{j.schedule}</code></td><td><label className="method">{j.method}</label></td><td><button className={'pill '+(j.enabled?'on':'')}onClick={()=>toggle(j,{enabled:!j.enabled})}><span/>{j.enabled?'Active':'Paused'}</button></td><td>{j.last_run_at?<><strong>{ago(j.last_run_at)}</strong><small className={j.last_status==='failed'?'red':''}>{j.last_status}</small></>:<span className="muted">Never</span>}</td><td><div className="actions"><button onClick={()=>run(j)}>▶</button><button onClick={()=>edit(j)}>✎</button><button onClick={()=>dup(j)}>⧉</button><button onClick={()=>del(j)}>⌫</button></div></td></tr>)}</tbody></table></div>:<Empty create={create}/>}</section>}
function JobRow({j,run,toggle,open}){return <button className="jobrow"onClick={()=>open(j)}><i>◉</i><span><strong>{j.name}</strong><small>{j.url}</small></span><label>{schedules[j.schedule]||j.schedule}</label><b className={j.last_status||'never'}>{j.last_status==='success'?'✓ Success':j.last_status==='failed'?'! Failed':'Never run'}</b><aside><button onClick={e=>{e.stopPropagation();run(j)}}>▶</button><button onClick={e=>{e.stopPropagation();toggle(j,{enabled:!j.enabled})}}>{j.enabled?'Ⅱ':'▶'}</button></aside></button>}
function History({data,refresh}){return <section className="panel full"><Head title="Execution History"sub="Response codes, latency, timestamps, and failures."action="↻ Refresh"onClick={refresh}/>{data.length?<div className="table"><table><thead><tr><th>Job</th><th>Started</th><th>Result</th><th>HTTP</th><th>Duration</th><th>Error</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td><strong>{x.job_name||x.job_id}</strong></td><td>{new Date(x.started_at).toLocaleString()}</td><td><label className={'result '+x.status}>{x.status==='success'?'SUCCESS':'FAILED'}</label></td><td>{x.status_code||'—'}</td><td>{x.response_time_ms?x.response_time_ms+' ms':'—'}</td><td className="error">{x.error_message||'—'}</td></tr>)}</tbody></table></div>:<EmptyText/>}</section>}
function Drawer({job,history,close,edit,run,del,dup}){return <div className="overlay"onMouseDown={close}><aside className="drawer"onMouseDown={e=>e.stopPropagation()}><div className="drawerhead"><div><small>CRON JOB</small><h2>{job.name}</h2></div><button onClick={close}>×</button></div><div className="url">{job.url}</div><div className="details"><div><small>Schedule</small><strong>{schedules[job.schedule]||'Custom'}</strong><code>{job.schedule}</code></div><div><small>Method</small><strong>{job.method}</strong></div><div><small>Timezone</small><strong>{job.timezone}</strong></div><div><small>Status</small><strong className={job.enabled?'green':'muted'}>{job.enabled?'Active':'Paused'}</strong></div></div><div className="drawerbuttons"><button className="primary"onClick={run}>▶ Run now</button><button onClick={edit}>✎ Edit</button><button onClick={dup}>⧉ Duplicate</button><button className="danger"onClick={del}>Delete</button></div><h3>Recent runs</h3>{history.slice(0,8).map(x=><div className="drawerrow"key={x.id}><span className={'dot '+x.status}/><span>{new Date(x.started_at).toLocaleString()}</span><b>{x.status_code||'ERR'}</b><small>{x.response_time_ms?x.response_time_ms+'ms':x.error_message||'—'}</small></div>)}{!history.length&&<p className="muted">No executions yet.</p>}</aside></div>}
function Modal({job,close,save}){let f=job?{...job,headers:JSON.stringify(job.headers||{},null,2),body:job.body||''}:formDefaults();return <div className="overlay"onMouseDown={close}><form className="modal"onSubmit={save}onMouseDown={e=>e.stopPropagation()}><div className="modalhead"><div><small>{job?'EDIT AUTOMATION':'NEW AUTOMATION'}</small><h2>{job?'Edit Cron Job':'Create Cron Job'}</h2></div><button type="button"onClick={close}>×</button></div><div className="grid"><label>Job name<input name="name"required defaultValue={f.name}placeholder="Website health check"/></label><label>Method<select name="method"defaultValue={f.method}>{['GET','POST','PUT','PATCH','DELETE','HEAD'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>URL<input name="url"type="url"required defaultValue={f.url}placeholder="https://example.com/api/health"/></label><div className="grid"><label>Schedule<select name="schedule"defaultValue={f.schedule}>{Object.entries(schedules).map(([v,l])=><option value={v}key={v}>{l}</option>)}<option value={f.schedule}>{f.schedule}</option></select></label><label>Timezone<input name="timezone"defaultValue={f.timezone}/></label></div><label>Headers <small>JSON</small><textarea name="headers"rows="4"defaultValue={f.headers}/></label><label>Request body <small>Optional</small><textarea name="body"rows="4"defaultValue={f.body}placeholder='{"event":"heartbeat"}'/></label><footer><span>30 second request timeout</span><button type="button"onClick={close}>Cancel</button><button className="primary">{job?'Save changes':'Create Job'}</button></footer></form></div>}
function Settings({user}){return <section className="panel settings"><Head title="Account settings"sub="Your CronFlow account."/><div className="profile"><b>{user.email?.[0]?.toUpperCase()}</b><div><strong>{user.email}</strong><span>Free plan</span></div></div><div className="setting"><span>Account ID</span><code>{user.id}</code></div><div className="setting"><span>Local timezone</span><strong>{TZ}</strong></div></section>}
function Head({title,sub,action,onClick,primary}){return <div className="panelhead"><div><h2>{title}</h2><p>{sub}</p></div>{action&&<button className={primary?'primary':'secondary'}onClick={onClick}>{action}</button>}</div>}
function Stat({t,v,i,bad}){return <div className="stat"><i className={bad?'bad':''}>{i}</i><span>{t}</span><strong>{v}</strong></div>}
function Empty({create}){return <div className="empty"><div>◷</div><h3>No cron jobs found</h3><p>Create a scheduled HTTP request and CronFlow will execute it automatically.</p><button className="primary"onClick={create}>Create your first job</button></div>}
function EmptyText(){return <div className="empty"><div>↻</div><h3>No executions yet</h3><p>Run a cron job and its result will appear here.</p></div>}
function Landing({mode,setMode,onAuth}){return <div className="landing"><header><div className="brand"><i>C</i>CronFlow <b>2.0</b></div><div><button onClick={()=>setMode('login')}>Log in</button><button className="primary"onClick={()=>setMode('signup')}>Get started</button></div></header><section className="hero"><small>● SIMPLE HTTP CRON SCHEDULER</small><h1>Automate your web tasks.<br/><em>Set it and forget it.</em></h1><p>Schedule HTTP requests, monitor every execution, and keep your APIs running automatically.</p><button className="primary large"onClick={()=>setMode('signup')}>Create free account →</button></section><div className="features"><Feature i="◷"t="Flexible schedules"p="Minute-to-month schedules, expressions, and timezones."/><Feature i="↻"t="Execution history"p="Response codes, latency, timestamps, and failures."/><Feature i="✓"t="Full job control"p="Pause, resume, edit, duplicate, test, and delete."/></div><Auth mode={mode}setMode={setMode}onAuth={onAuth}/></div>}
function Feature({i,t,p}){return <div><i>{i}</i><h3>{t}</h3><p>{p}</p></div>}
function Auth({mode,setMode,onAuth}){let[e,setE]=useState(''),[p,setP]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);async function submit(x){x.preventDefault();setBusy(true);setErr('');try{let r=await api(`/api/auth/${mode==='login'?'login':'register'}`,{method:'POST',body:JSON.stringify({email:e,password:p})},null),d=await r.json();if(!r.ok){setErr(d.error||'Authentication failed');return}localStorage.setItem(KEY,d.token);onAuth(d.user)}catch{setErr('Could not connect to CronFlow')}finally{setBusy(false)}}return <form className="auth"onSubmit={submit}><div className="brand"><i>C</i>CronFlow</div><h2>{mode==='login'?'Welcome back':'Create your account'}</h2>{err&&<div className="autherr">{err}</div>}<label>Email<input type="email"required value={e}onChange={x=>setE(x.target.value)}/></label><label>Password<input type="password"required minLength="8"value={p}onChange={x=>setP(x.target.value)}/></label><button className="primary full"disabled={busy}>{busy?'Please wait...':mode==='login'?'Log in':'Create account'}</button><button type="button"className="switch"onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create an account':'Back to login'}</button></form>}
createRoot(document.getElementById('root')).render(<App/>);
